

def vistaRegiones(cursor):
	cursor.execute(
		"""
			CREATE OR REPLACE VIEW REGIONES AS
			SELECT ID_REGION, NOMBRE_REGION, SUM(CASOS_CONFIRMADOS) AS CASOS_CONFIRMADOS, SUM(POBLACION) AS POBLACION FROM CASOS_POR_REGION GROUP BY ID_REGION, NOMBRE_REGION
		"""
		)
