def vistaRegiones(cursor):
	cursor.execute(
		"""
			CREATE OR REPLACE VIEW POSITIVIDAD_REG AS
			SELECT ID_REGION, ROUND((NOMBRE_REGION, CASOS_CONFIRMADOS/POBLACION)*100,2) AS POSITIVIDAD_REGIONAL FROM CASOS_POR_REGION ORDER BY POSITIVIDAD_REGIONAL DESC
		)
