def positividadRegiones(cursor):
	cursor.execute(
		"""
			CREATE OR REPLACE VIEW POSITIVIDAD_REG AS
			SELECT NOMBRE_REGION, ROUND(((CASOS_CONFIRMADOS/POBLACION)*100),2) AS POSITIVIDAD_REGIONAL
			FROM CASOS_POR_REGION
			WHERE POBLACION <> 0
			ORDER BY POSITIVIDAD_REGIONAL DESC
		"""
		)

def positividadComunas(cursor):
	cursor.execute(
		"""
			CREATE OR REPLACE VIEW POSITIVIDAD_COM AS
			SELECT NOMBRE_COMUNA, ROUND(((CASOS_CONFIRMADOS/POBLACION)*100),2) AS POSITIVIDAD_COMUNAL
			FROM CASOS_POR_COMUNA
			WHERE POBLACION <> 0
			ORDER BY POSITIVIDAD_COMUNAL DESC
		"""
		)
